### PR TITLE
Fix text string

### PR DESCRIPTION
**Pull request by Atalanttore**

### CODE REVIEW

**Comment by yan12125** [comment]
There's another "Keyboard Cursor Shape" in the `View` menu.

And I would say simply "Cursor shape" is fine.

**Comment by yan12125** [comment]
@shlyakpavel We are on the same line :)

**Comment by agaida** [comment]
@yan12125 @shlyakpavel  - better? Btw, @yan12125 - you should be able to change PRs directly

**Comment by yan12125** [comment]
Thanks for the update! First I was hesitated without a comment from the original author, then I forgot about this PR lol

**Pull request merged**
