### PR TITLE
Trim shell QString.

### PR DESCRIPTION
**Pull request by textbrowser**

### CODE REVIEW

**Comment by yan12125** [comment]
Thanks for the fix! Could you do trimming inside `getShell()`? If there are other usages of `getShell()` in the future, they will be benefited as well.

**Comment by textbrowser** [comment]
Also changed getShell().

**Comment by textbrowser** [comment]
How about trimming the strings in the conditionals? For example
```if(!m_shell.trimmed().isEmpty())```.

**Comment by yan12125** [comment]
> How about trimming the strings in the conditionals?

That sounds better!

**Comment by yan12125** [comment]
Thanks! I think the change in  src/termwidget.cpp is no longer needed?

**Comment by textbrowser** [comment]
Yes, please discard that change.

**Comment by yan12125** [comment]
> Yes, please discard that change.

GitHub does not seem to allow merge only some commits. Could you do that locally with git? Squashing previous commits is fine.

**Comment by textbrowser** [comment]
I've reverted the "index-verification" push. I'm sorry for including that revision with this pull request.

**Comment by yan12125** [comment]
No problem and thanks!

**Pull request merged**
