### PR TITLE
Adding same new issue templates as in lxqt

### PR DESCRIPTION
**Pull request by stefonarch**

### CODE REVIEW

**Comment by yan12125** [comment]
Actually there is already an issue template https://github.com/lxqt/qterminal/blob/master/.github/ISSUE_TEMPLATE.md. We cannot stop users from ignoring it, sigh.

**Comment by yan12125** [comment]
Or do you mean to replace the existing issue template with those new ones? Then remove the old one.

At a first glance,  `liblxqt Version` in bug_report.md is not needed for qterminal as liblxqt is not a dependency

**Comment by stefonarch** [comment]
The existing one will not be used anymore. To see iin action: https://github.com/lxqt/lxqt/issues/new/choose


> At a first glance, `liblxqt Version` in bug_report.md is not needed for qterminal as liblxqt is not a dependency

Sure, I just copied over the templates which I used in lxqt/lxqt, will remove this.

**Comment by stefonarch** [comment]
adapted to Qterminal now

**Comment by yan12125** [comment]
Looks great! Could you replace all "Qterminal" with "QTerminal"? That seems the official name https://github.com/lxqt/qterminal#readme

> The existing one will not be used anymore. 

Then go ahead and remove it!

**Comment by stefonarch** [comment]
Done, also reworded the warnings about LTS user in bug report template.

**Comment by yan12125** [comment]
Awesome! Thanks a lot.

**Pull request merged**
