### PR TITLE
Handle bell (BEL, '\a') via libcanberra

### PR DESCRIPTION
**Pull request by yan12125**
Tested with `echo -e "\07"`

Closes https://github.com/lxqt/qterminal/issues/355

### CODE REVIEW

**Comment by tsujan** [comment]
Works as intended.

**Comment by tsujan** [comment]
Nice feature, BTW. My terminal isn't silent anymore :)

**Comment by yan12125** [comment]
By the way, I'm not sure if people feel terminal bells noisy. Pulseaudio allows disabling sounds from specific applications (ex: qterminal), and I believe other sound servers provide similar functionality. This should not be an issue, anyway.

**Comment by Chiitoo** [comment]
> By the way, I'm not sure if people feel terminal bells noisy. Pulseaudio allows disabling sounds from specific applications (ex: qterminal), and I believe other sound servers provide similar functionality. This should not be an issue, anyway.

Definitely something I (and others I know) have on a checklist to disable when installing something like an Ubuntu workstation (though I usually install LXQt and friends as well so I won't be using the GNOME things in any case).

My personal machines use plain ALSA only, so silencing a single application isn't that simple, so it would certainly be nice to have an option to disable this feature (while 'libcanberra' may be installed for other reasons).

**Comment by tsujan** [comment]
If an option for disabling it is going to be added, please do it after merging this PR. IMHO, it's good to keep this PR only for its implementation.

**Comment by yan12125** [comment]
Thanks for the information about ALSA. I will add an option after this PR.

**Review by luis-pereira — APPROVED** [review]
It works Ok. The code is Ok.
GTM.

**Comment by luis-pereira** [comment]
Wrote https://github.com/lxqt/qterminal/pull/new/add-audible-bell-option for enabling/disabling audible bell.

**Comment by yan12125** [comment]
Thanks! Could you push new commits to this branch (wip-support-bell) instead? It's better to merge them together.

**Comment by luis-pereira** [comment]
> Thanks! Could you push new commits to this branch (wip-support-bell) instead? It's better to merge them together.

Done. Force pushed due to changes in my commit message.
Consider removing the wip from the branch name,

**Comment by yan12125** [comment]
Thanks, your part looks good and it works as expected.

A side note: `<tabstop>dropShortCutEdit</tabstop>` in the UI file is no longer relevant after https://github.com/lxqt/qterminal/pull/910.

> Consider removing the wip from the branch name,

Apparently GitHub does not allow changing the source branch for an existing pull request. The source branch name does not appear in a commit message with Rebase and merge or Squash and merge, anyway.

**Pull request merged**
