### PR TITLE
Allow a build with Qt 6

### PR DESCRIPTION
**Pull request by tsimonq2**
WIP, since QTerminal doesn't actually display anything yet.

### CODE REVIEW

**Comment by yan12125** [comment]
I prefer to completely move to Qt 6 and drop support for Qt 5. See discussions at https://github.com/lxqt/qtermwidget/pull/468.

Marking as draft for now. Feel free to mark it as ready by yourself later.

**Comment by tsimonq2** [comment]
Sounds good, thank you @yan12125! :smile:

**Comment by epasveer** [comment]
Sorry to prod.  Any update on a Qt6 release for qterminal?

Thanks.

**Comment by yan12125** [comment]
> I prefer to completely move to Qt 6 and drop support for Qt 5.

I updated this branch to include only Qt 6 support. Not tested yet, though.

> Sorry to prod. Any update on a Qt6 release for qterminal?

After this branch and https://github.com/lxqt/qtermwidget/pull/532 are merged, qterminal should work with Qt 6.

There is still a technical issue: pyqt support in qtermwidget gets broken during qt 6 migration (see the qtermwidget PR for more details). May need some time to investigate.

**Comment by epasveer** [comment]
> qterminal should work with Qt 6.

Thanks for the update. Looking forward to trying it.

**Comment by yan12125** [comment]
I noticed some of my local changes overlap with https://github.com/lxqt/qterminal/pull/1110. I will push my remaining changes there.

**Pull request merged**
