### PR TITLE
Translation update

### PR DESCRIPTION
**Pull request by crazyraven**
Hi.
I've created Korean translation file for your qterminal. Hope this one could be merged to your repo.
If there are any mistakes or something need to be corrected in this file, please let me know.
Thank you.

### CODE REVIEW

**Comment by yan12125** [comment]
Thank you for contribution! At the first glance this looks good. Let's see if [Weblate](https://weblate.lxqt.org/projects/lxqt/qterminal/) likes it or not.

**Comment by yan12125** [comment]
Now those translations are imported to Weblate :) https://weblate.lxqt.org/translate/lxqt/qterminal/ko/?type=all

Here's a question: colons in English are omitted in Korean. Is it the usual practice for Korean applications?

**Comment by crazyraven** [comment]
What a my mistake! That's not usual I'll make a correction via weblate soon :) Thank you for merging.

**Comment by crazyraven** [comment]
corrections have made via weblate. please review it. :)
Thank you.

**Comment by yan12125** [comment]
Review still happens on GitHub :) In Weblate, you can use Manage -> Repository Maintanence -> Commit and then Push to get a pull request on GitHub like https://github.com/lxqt/qterminal/pull/539.

**Pull request merged**
