### PR TITLE
Fixed version comparison

### PR DESCRIPTION
**Pull request by tsujan**
Fixes https://github.com/lxqt/qterminal/issues/616

### CODE REVIEW

**Comment by agaida** [comment]
https://doc.qt.io/qt-5/qversionnumber.html

**Comment by tsujan** [comment]
No need to it.

**Comment by agaida** [comment]
i just want to mention it.

**Comment by tsujan** [comment]
Thanks! It's quite good to use it. Tastes differ though: I prefer to add my simple functions when a whole class isn't needed.

That being said, if you feel it's really necessary to add that class, it'll be OK to me.

**Comment by agaida** [comment]
Your PR is good - and it is not needed to use qversionnumber

**Pull request merged**
