### PR TITLE
Fixed some issues with the tabwidget class and Fixed the profile issue

### PR DESCRIPTION
**Pull request by agaida**
without the last commit

### CODE REVIEW

**Comment by tsujan** [comment]
Does it solve the problem? I's just checked the code for errors.

**Comment by agaida** [comment]
no FTBFS, no warnings

**Comment by tsujan** [comment]
I know; I meant the profile issue. It fixes a crash in tabs.

**Comment by Geo25rey** [comment]
I fixed the FTBFS on the latest commit. Sorry about the trouble. If I have any bug fixes in the future, I'll separate the PRs.

**Pull request closed without merging**
