### PR TITLE
Add shortcut editing instructions

### PR DESCRIPTION
**Pull request by radiocane**
I've added some instructions for editing QTerminal shortcuts, just above the Shortcut/Key list.

### CODE REVIEW

**Comment by tsujan** [comment]
Labels can take too much space and make the widget too wide, especially with translations. Tooltips (and "What's This") specialize in showing info without cluttering the GUI. The same info can be added as the tooltip of `shortcutsWidget`.

BTW, `3 click on a Shortcut` isn't necessary. The user can press `Enter`.

**Comment by radiocane** [comment]
Bumping after commit

**Comment by tsujan** [comment]
Requested @yan12125's review. He knows QTerminal better than all.

**Comment by yan12125** [comment]
Thanks for this! Looks good overall. Just some minor comments:

* Better to add a dot after numbers -> `1.` `2.`
* Better to capitalize the first word for each item

> `3 click on a Shortcut` isn't necessary.

Well, clicking on the shortcut is what I do. It is more intuitive for me. I would put both approaches in the tooltip.

**Comment by yan12125** [comment]
Thanks!

**Pull request merged**
