### PR TITLE
Tidy

### PR DESCRIPTION
**Pull request by luis-pereira**

### CODE REVIEW

**Review by tsujan — APPROVED** [review]
LGTM.

@yan12125, can it be merged before I make a pre-release PR?

**Comment by yan12125** [comment]
Probably not. Some changes are not trivial, and I don't have time to dive into it these days.

**Comment by tsujan** [comment]
> Probably not.

It's OK with me.

**Comment by yan12125** [comment]
At a glance those changes look good,  but I still don't have time to investigate into details. As this pull request has been stuck for too long, let's test it in git-master instead.

**Pull request merged**
