### PR TITLE
Fixed shortcut setting when the Key column is sorted

### PR DESCRIPTION
**Pull request by tsujan**
The bug was very old. I noticed it by chance.

Fixes https://github.com/lxqt/qterminal/issues/729

### CODE REVIEW

**Comment by tsujan** [comment]
@yan12125, I requested a review from you. Please tell me if you don't have time before November 4 because, IMHO, it should be in 0.16.0.

**Comment by yan12125** [comment]
Had a quick look and it seems reasonable. If you want to have it in 0.16, go ahead! Otherwise, this needs to be postponed to 0.17 if you want an in-depth review.

**Comment by tsujan** [comment]
@yan12125 
In the old code, it was supposed that the order of actions should be the same in the app and in the shortcut table. Since that mistake could totally ruin shortcuts, I think this should be in 0.16.0.

**Comment by tsujan** [comment]
BTW, the remainder of the old shortcut code has another problem, which it isn't critical and can wait.

**Pull request merged**
