### PR TITLE
Update qterminal_pt_BR.ts

### PR DESCRIPTION
**Pull request by bugcrazy**
Fix translation errors, removal of numeric characters in the translation that do not exist in the original.

### CODE REVIEW

**Comment by yan12125** [comment]
Thanks for the fix! I wonder why the original translation passed the review :thinking:

**Comment by bugcrazy** [comment]
I really like the LXQt project. I hope the project will evolve and advance to version 1.0.0

**Comment by yan12125** [comment]
Glad to hear that :)

**Comment by agaida** [comment]
PS: We use [Weblate](https://weblate.lxqt.org/translate/lxqt/qterminal/pt_BR/?checksum=&offset=&q=Which+behavior+to+emulate.+Note+that+this+d&search=ftx&source=on&target=on&type=all&ignored=False&date=&only_user=&exclude_user=) - and i am surprised, that this change is merged in Weblate - normally it breaks weblate and the work is lost :) - ok, including the work of other Translators in this file - so please:

**Translation changes only in Weblate! Thanks :smile:**

**Comment by yan12125** [comment]
I remember GitHub pull requests for translations are not discouraged? Or things have changed?

**Comment by agaida** [comment]
Only a year ago or so - not discouraged are PRs for desktop files and completly new translations.
But you are right, we should do some more documentation. To be honest i would like to postpone it a bit, just experimenting with wiki,js and it looks promising. And since yesterday i don't want to put all eggs into one basket to be honest. (@tsujans remarks about github restrictions)

**Comment by tsujan** [comment]
> @tsujans remarks about github restrictions

Until now, those restrictions have been only for me (because of a new kind of discrimination) and they seem to be just a formality (there has been no practical change). I try to ignore them but, last night, I created a GitLab account and started mirroring from GitHub -- better be safe than sorry.

**Comment by yan12125** [comment]
Ah, thanks for the explanations!

**Pull request merged**
