### PR TITLE
Fixed inactive tab text with Qt6

### PR DESCRIPTION
**Pull request by tsujan**
Due to a change (or bug?) in Qt6, using a stylesheet for setting the font of active/inactive tabs doesn't work as it did with Qt5.

Here, `QStyle` is used directly, which is always the best approach because stylesheets can interfere with the widget style in bad ways.

Fixes https://github.com/lxqt/qterminal/issues/1112

### CODE REVIEW

**Comment by tsujan** [comment]
@yan12125 
This is needed before releasing Qt6 QTerminal.

**Comment by luis-pereira** [comment]
Works as described with 6.6.2.

**Comment by yan12125** [comment]
Thanks! Although I don't fully understand QStyle, I trust your expertise.

**Comment by tsujan** [comment]
@yan12125,
Any estimation about when QTerminal 2.0.0 can be released? I haven't found any performance issue so far, but it may be better to silence compilation warnings before releasing.

**Comment by yan12125** [comment]
I have some local changes for minor fixes and improvements, which should be finished in one or two days. Besides that, I'm waiting for https://github.com/lxqt/qterminal/pull/1110 and https://github.com/lxqt/qtermwidget/pull/540.

**Pull request merged**
