### PR TITLE
Added an option for borderless state and remembered it

### PR DESCRIPTION
**Pull request by tsujan**
There was an incorrect assumption in the code, that had resulted in overlooking it.

### CODE REVIEW

**Comment by tsujan** [comment]
Oh, there is still a problem. I'll tell you when it's fixed.

**Comment by agaida** [comment]
ok, fine - what do you think about an explicit option for?

**Comment by tsujan** [comment]
I fixed the problem. It can be tested now.

> what do you think about an explicit option for?

No objection. Let the main bug be fixed by this patch and then we could add an option for it to Preferences, although I think it'll be a sort of duplication.

**Comment by tsujan** [comment]
An explanation:

When I said "there is still a problem", I saw that changing an option in Preferences made the borderless window disappear. I think the original author encountered the same problem and ignored borederlessness because of it. But it had a simple solution. that is inside the patch now.

**Comment by tsujan** [comment]
@agaida I listened to you and added a separate commit to this PR for an option in Preferences dialog. There was a duplicate option for hiding menubar; so, why not another one for borderlessness? Moreover, a future PR would change this patch; hence doing them together, in the current PR.

**Comment by agaida** [comment]
@tsujan - thank you very much. I see the possibility  of cluttering the settings page too - with a big but: BUT we should integrate senseful options, no matter how hard it is for us. And i really mean it: For me it is easy to ask for an option that it is otherwise not visible (at a first sight) for the normal user. And i really mean it - Read the not yet done fucking manual can't be the only answer, so this is a really sensible thing - we know "option orgies" in other applications, might it be terminals or editors - I would've be fine if your answer had been: Not a visible option first hand, but doable in the config file-

**Comment by tsujan** [comment]
@agaida After giving it more thought and considering different use cases, I came to the same conclusion; otherwise, I wouldn't change the title. So, I completely agree with you :)

**Comment by travankor** [comment]
you guys should cut a new release once you merge this

**Comment by tsujan** [comment]
> you guys should cut a new release once you merge this

As far as I know, the whole LXQt will be released soon, the last release being really old now.

**Comment by tsujan** [comment]
I think this can be merged for git users. @yan12125, do you see any problem?

**Comment by yan12125** [comment]
Sorry I haven't had time to actually test this. The code looks OK, so let's give it a try!

**Pull request merged**
