### PR TITLE
Put drop-down QTerminal on screen with cursor

### PR DESCRIPTION
**Pull request by tsujan**
And resize it accordingly.

Closes https://github.com/lxqt/qterminal/issues/715

### CODE REVIEW

**Comment by yan12125** [comment]
Does this count as an "exciting feature" mentioned in https://github.com/lxqt/lxqt/issues/1848#issuecomment-714323140?

**Comment by tsujan** [comment]
> Does this count as an "exciting feature" mentioned in lxqt/lxqt#1848 (comment)?

No :) It's trivial. By "exciting feature" I meant a complex change.

**Comment by yan12125** [comment]
The code change looks logical and the new behavior looks good, thanks!

**Comment by tsujan** [comment]
@yan12125, thanks for reviewing! I also tested it with two screens by changing their resolutions.

**Pull request merged**
