### PR TITLE
WIP: Proper version comparison.

### PR DESCRIPTION
**Pull request by Andersbakken**

### CODE REVIEW

**Comment by agaida** [comment]
is this really needed?

**Comment by tsujan** [comment]
> is this really needed?

I don't think so. Let's hear what @yan12125 might say.

**Comment by yan12125** [comment]
The issue this tries to fix is real. However, I'd prefer another approach - just removing version conditions and migrate settings. I've heard many users follow git-master, making version numbers no longer accurate.

**Comment by agaida** [comment]
given that we will have migrations from time to time - i've nothing against, ls long the implementation is clean.

**Comment by agaida** [comment]
Btw - why is an exact match needed? Migrate all things < 0.14 and be done with. Or do i forget something?

**Comment by yan12125** [comment]
Superseded by more-robust and simpler https://github.com/lxqt/qterminal/pull/617.

**Pull request closed without merging**
