### PR TITLE
Added hint on dopdown shortcut under Wayland

### PR DESCRIPTION
**Pull request by tsujan**
… to Terminal settings → Dropdown → Shortcut.

### CODE REVIEW

**Review by stefonarch — COMMENTED** [review]
IMHO the text shouldn't be personal with "you" but neutral, kind of : "Note: A shortcut for qterminal -d has to be added manually in the compositor settings". Afaik we use this on other places too.

**Comment by tsujan** [comment]
(1) That "manually" can be confusing; some compositors may have GUI for it. (2) "A shortcut" is also confusing; we want to say concisely that this very shortcut won't work on Wayland unless added to the compositor. (3) Direct sentences are usually preferable. And (4) QTerminal is used by a person ;)

**Comment by stefonarch** [comment]
Sure, manually is weird, but you use your hands also in a GUI ;)

immagine

**Comment by tsujan** [comment]
Are you happy with "Note: On Wayland, the shortcut has to be added in the compositor settings for 'qterminal -d'."? I put `for 'qterminal -d'` at the end intentionally because the shortcut has the same role but is for that command on Wayland.

**Comment by stefonarch** [comment]
I'm ok with that text, it's clear and in line with other notes.

**Comment by tsujan** [comment]
Done.

**Review by stefonarch — APPROVED** [review]

**Pull request merged**
