### PR TITLE
Warnings

### PR DESCRIPTION
**Pull request by luis-pereira**

### CODE REVIEW

**Comment by tsujan** [comment]
Already done in https://github.com/lxqt/qterminal/pull/1124

**Comment by tsujan** [comment]
Please also see https://github.com/lxqt/qtermwidget/pull/549

**Comment by luis-pereira** [comment]
> Already done in #1124

Hummm wasn't aware. Closing.

**Comment by luis-pereira** [comment]
> Please also see [lxqt/qtermwidget#549](https://github.com/lxqt/qtermwidget/pull/549)

Will look.

**Pull request closed without merging**
